version: '3.8'
services:
  backend:
    build:
      context: ./supply-chain-backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./supply-chain-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
